#!/usr/bin/env python3
from pokerstove import *

r1 = Rank()
r2 = Rank(4)
r3 = Rank('4')
print('-- rank --')
print(r1, r2, r3)
s = {r1, r2, r3}

s1 = Suit()
s2 = Suit(2)
s3 = Suit('c')
print('-- suits --')
print(s1, s2, s3)

c1 = Card()
c2 = Card(2)
c3 = Card('As')
print('-- cards --')
print(c1, c2, c3)
s = {c1, c2, c3}
l = [c1, c2, c3]

cs1 = CardSet()
cs2 = CardSet(0x8E)
cs3 = CardSet('AcAh8c8d2s')
cs4 = CardSet('Ah8h')
cs5 = CardSet('Ac8dKc')
print('-- card sets --')
print('empty card set: ', cs1)
print(cs2, cs3, cs4)
s = {cs1, cs2, cs3, cs4, cs5}

e1 = PokerEvaluation()
e2 = PokerEvaluation(26214408)
e3 = PokerEvaluation(58720800)
print('-- poker evals --')
print('null eval:', e1)
print(e2)
print(e3)

h1 = PokerHandEvaluation()
h2 = PokerHandEvaluation(e2)
h3 = PokerHandEvaluation(e3)
print('-- poker hand evals --')
print('h1: ', h1)
print('h2: ', h2)
print('h3: ', h3)

print('-- poker hand --')
ph1 = PokerHand()
ph2 = PokerHand(cs3)
ph3 = PokerHand('acAd3c4s5h6d7c')
print('ph1: ', ph1)
print('ph2: ', ph2)
print('ph3: ', ph3)
cards = ph3.cards()
print('card list: ', len(cards), cards)

print('-- holdem hand evaluation --')
v = PokerHandEvaluator.alloc('h')
e4 = v.evaluateHand(cs4)
e5 = v.evaluateHand(cs4, cs5)
print(e4)
print(e5)

print('-- omaha hand evaluation --')
cs6 = CardSet('AcAd2sKc')
brd = CardSet('4c5h8c9dJs')
v = PokerHandEvaluator.alloc('o8')
e6 = v.evaluateHand(cs6, brd)
print(e6)
evals = e6.evals()
print('number of evals: ', e6.size())
print('length of evals: ', len(evals))
print('actual evals: ', evals)
e7 = v.evaluateHand(cs6)
print('omaha, no board: ', e7.evals())

print('-- holdem facts --')
print('holdem board size: ', BOARD_SIZE)
print('num holdem rounds: ', NUM_HOLDEM_ROUNDS)

print('-- simple deck --')
d = SimpleDeck()
# note the deck is split into two sets {live}/{dead}
print('deck: ', d)
d.shuffle()
print('deck: ', d)
bottom = d.peek(3)
top = d.peek(0x8000000000000)
burn = d.deal(1)
pocket = d.deal(2)
flop = d.deal(3)
dead = d.dead()
print('peek bottom: ', bottom)
print('peek top: ', top)
print('burn: ', burn)
print('holdem: ', pocket, flop)
print('dealt (dead): ', dead)
print('deck: ', d)


